on_foot : False

# 已过滤不需要的标签，下面是全标签
# swords : ['sightseeing/', 'hiking/', 'mountaineering/', 'biking/', 'driving/', 'running/', 'cross_country/', 'mountain_biking/', 'motorcycling/', 'skiing/', 'skateboard/', 'water/']
# 非步行标签
# swords = [False, 'hiking/', 'mountaineering/', 'biking/', 'driving/', 'running/']
# 步行标签
# swords = [True, 'hiking/', 'running/']

# 省份对应的代号
pnum : ['30/',   '27/',   '32/', '31/', '29/', '28/',  '26/',   '25/',  '24/',
  '23/',  '22/', '21/', '20/', '19/', '18/', '17/', '16/', '15/', '14/', '13/', '12/'
  '11/', '10/', '9/', '8/', '7/', '6/', '5/', '4/', '3/', '2/']
# 省份名字
pname : ['青海', '西藏', '新疆', '宁夏', '甘肃', '陕西', '云南', '贵州', '四川',
 '重庆', '海南', '广西', '广东', '湖南', '湖北', '河南', '山东', '江西', '福建', '安徽', '浙江'
 '江苏', '上海', '黑龙江', '吉林', '辽宁', '内蒙古', '山西', '河北', '天津', '北京']

years : ['2025', '2024', '2023']

early_stop : 3